### ISSUE TITLE
Not working with React Native

### ISSUE THREAD

**Issue by rcfrias** [alan2207/react-query-auth#10]
As soon as you try to use the AuthProvider, the followin error appears:

ExceptionsManager.js:149 Error: Text strings must be rendered within a <Text> component.

**Comment by alan2207** [comment]
Hi there,

I am suspecting that the error is caused by these lines:
https://github.com/alan2207/react-query-auth/blob/5c35632bffa55eead0801dda4d0787e907759e07/src/index.tsx#L66
https://github.com/alan2207/react-query-auth/blob/5c35632bffa55eead0801dda4d0787e907759e07/src/index.tsx#L68

`div` is not valid element in RN, so you can try to provide your own `LoaderComponent ` and `ErrorComponent ` compatible with RN.

**Comment by ugoconsonni** [comment]
I modified the code to work with react native

**Comment by alan2207** [comment]
Hey folks, you might want to install the latest version, which is platform agnostic.
