### ISSUE TITLE
Feature Request: Ensure useUser Always Returns a User

### ISSUE THREAD

**Issue by Ganbin** [alan2207/react-query-auth#36]
#### Description  
Allow to have a `useUser` to always return a valid user object in certain context. This is particularly useful in authenticated pages where authentication is verified at the route level. In such cases, the presence of a logged-in user is assured, making additional checks for user existence unnecessary.

**Comment by Ganbin** [comment]
For now my "workaround" is to use the Tanstack Router context.

I have my restricted routes under a `_restricted` folder with this code :

```ts
export const Route = createFileRoute("/_restricted")({
  beforeLoad: async ({ context, location }) => {
    if (!context.user) {
      throw redirect({ search: { redirect: location.href }, to: "/login" });
    }
    const { user } = context;
    return { ...context, user };
  },
  component: () => <RestrictedRoot />,
});
```

And at the `App` level I have something like that :
```ts
const user = useUser();
return (
  <RouterProvider
    router={router}
    context={{
      queryClient,
      user: user.data ?? undefined,
    }}
  />
);
```

This allow me to narrow down the user inside my restricted route. I can then access the use with :
```ts
const { user } = Route.useRouteContext();
```
Instead of 
```ts
const { user } = useUser();
```

And then I'm sure `user` is defined.

**Comment by alan2207** [comment]
Hey @Ganbin, thanks for sharing! I don't know which version of the library you are using, but it is not relying on context anymore. `useUser` uses `useQuery` now and since the user can be null, it is safer to keep that in mind and treat it that way. However, if you want to modify something, feel free to just copy the source code and modify it in your project, it's pretty straigthforward.
